# left-side user profile
avatar: //www.evidaliahost.com/assets/vps/img/vps-ventajas2.png   #//www.hostafrica.co.za/wp-content/uploads/2018/03/vps_icon_opt.png
location:
email:
social:
  github:
  weibo:
  linkedin:

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gsc: # google custom search code
